### ISSUE TITLE
A La Carte doesn't seem to be working

### ISSUE THREAD

**Issue by MarkPWebb** [Hernanm0g/meteor_vuetify#15]
Am I missing something here? I cloned the repo as is, added my credentials, but the visualiser shows vuetify as taking up 1.09MB. I was able to get it down to ~600KB using meteor-vuetify-loader in a test project, but not using the meteor-vuetify boiler plate code.

I noticed that zer0th:meteor-vuetify-loader was below akryum:vue-component in packages, so adjusted that as per the instructions for the loader because this was the only difference I could find, but it made no difference.

**Comment by Hernanm0g** [comment]
Hi @MarkPWebb . Actually, the A-la-carte is working smoothly in my local server.

Please make a git pull to the latest version, and run `npm run visualize`

If that doesnt work: Check this out:

```javascript
/*--------  The magic goes here  --------*/
let Vuetify
if(Meteor.isDevelopment){
  // Use this import while developing
  Vuetify = require("vuetify/lib").default
} else {
  // IMPORTANT: Use this imports in production to reduce bundle size
  Vuetify = require("vuetify/lib/framework").default
  // require("vuetify/lib/util/colors")
  require("vuetify/lib/directives")
}

Vue.use(Vuetify)
```
If you want to see the low client bundle size, make sure you're importing 'vuetify/lib/framework' instead of 'vueitfy/lib'.

In `/imports/startup/plugins/vuetify.js`

If, after checking this, you still having a 1.09MB vuetify lib size at client, please make sure that all the routes inside `/imports/startup/plugins/router/routes` are imported asynchronously. ike this:
```javascript
const Home = ()=> import ('../../../../ui/pages/home/Home.vue') // Dynamic async import
```

Please, let me know your findings.

**Comment by Hernanm0g** [comment]
Hi @MarkPWebb.

I think i've found the problem
node is currently importing both libraries here:
```javascript
  if(Meteor.isDevelopment){
    // Use this import while developing
    Vuetify = require("vuetify/lib").default
  } else {
    // IMPORTANT: Use this imports in production to reduce bundle size
    Vuetify = require("vuetify/lib/framework").default
    // require("vuetify/lib/util/colors")
    require("vuetify/lib/directives")
  }
```

Dont know why, but treeshaking for imports may not work well in node. So I'll try to find a better solution. keep in touch

**Comment by Hernanm0g** [comment]
Hi again!!

Finally i had to remove the conditionals for vuetify's importation. I dont have time right now so i encourage you to colaborate if you feel it. 

Right now he wave this:

```javascript
// Use this import while developing
import Vuetify from "vuetify/lib"

// IMPORTANT: Use this imports in production to reduce bundle size
// import Vuetify from "vuetify/lib/framework"
// import "vuetify/lib/util/colors"
// import "vuetify/lib/directives"

// TODO: find a proper way to import based on a conditional
// if(Meteor.isDevelopment){ ... }
```

In production, you'll have to uncomment and comment lines, thats not the best solution... but works for now.
