### ISSUE TITLE
Running built app 

### ISSUE THREAD

**Issue by ackzell** [Hernanm0g/meteor_vuetify#19]
This is an awesome idea, thanks for sharing your boilerplate @Hernanm0g!

I just wanted to point out that in my team we are trying to manually deploy the app. Though we are facing some issues, like the one pointed out in https://github.com/meteor-vue/vue-meteor/pull/415.

We pinned the version of Vue to `2.6.10` and although not ideal, this would probably do. 

Unfortunately we are now at this point, where a Vuetify file seems to be missing ( perhaps misplaced? )

Here you can see me trying to run the built app (uncompressed the result of `$ meteor build` and installed the dependencies on the `/bundle/programs/server` folder) and after this command :

`$ PORT=8086 node main` and visiting `http://localhost:8086`

I am getting:

```
Error: ENOENT: no such file or directory, open '/home/ackzell/tmp/builtApp/bundle/programs/server/node_modules/vuetify/dist/vuetify.min.css'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at imports/startup/server/index.js:59:32
    at new Promise (<anonymous>)
    at Object.VueSSR.createApp (imports/startup/server/index.js:44:12)
    at packages/akryum:vue-ssr/server/index.js:96:31
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/akryum:vue-ssr/server/index.js:86:23
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/akryum:vue-ssr/server/index.js:81:24
    at new Promise (<anonymous>)
    at packages/akryum:vue-ssr/server/index.js:73:20
    at packages/server-render/server-register.js:14:19
    at packages/server-render/server.js:28:36
    at /home/ackzell/tmp/builtApp/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fib                                                                                                                       ber_pool.js:43:40 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/ackzell/tmp/builtApp/bundle/programs/server/node_modules/vuetify/dist/vuetify.min.css'
}
```

Thanks a lot for the hard work and hopefully you can give me some pointers here.

Cheers!

**Comment by Hernanm0g** [comment]
Hey @ackzell. Ssr in production must be fixed now. Please be aware that:
1. I had to add vue-ssr package to the packages folder, and in package.js i had to explicitly set vue-server-renderer to version 2.6.12. (This will fix the version mistmatching. You will need to change this version to match the vue version you use in your ptoject)
2. in /imports/startup/server/index.js, its necessary to add /npm to the path where vuetify.min.css is loaded from (this will fix the problem loading css in production's ssr)

Hope that helps. enjoy.
