### ISSUE TITLE
v-switch rendered as checkbox 

### ISSUE THREAD

**Issue by ArosPrince** [Hernanm0g/meteor_vuetify#27]
Hi,
first off, thanks for this boiler plate. Very handy.

I've been having this very strange issue. If I try to add v-switch in any page or in any component, it is always rendered as a checkbox. No matter what I do, I cannot track that down. I tried creating a plain vuetify project (no meteor, no boilerplate) and there it works without any problems.

I tried to google it, but noone seems to be having this issue. Any idea what could be causing it? Could it some CSS in the boilerplate changing the style? Sorry if these are stupid questions, I am kinda new to frontend development...

Example:
looks like this:
![image](https://user-images.githubusercontent.com/25080989/141364823-14c3861e-4308-43bf-aea9-eb35ebef82f6.png)

But it should look like this:
![image](https://user-images.githubusercontent.com/25080989/141364884-0986c186-8867-43ef-8ba2-223076ebcbe3.png)

(the wrench button is irrelevant, it's just for the size reference)

Thanks
Jan

**Comment by ArosPrince** [comment]
Hm, weird. So I had a same problem with v-slider. It was not rendered at all.

But then I added it to the parent page itself and then it started working also in the subcomponents. I removed it from the page again, but it did not return to the weird state and still works. Even after restarting meteor.

Any ideas what could be causing it? Looks like some kind of caching is at play.

Let me also correct one thing it the OP. I obviously tried adding it to different components, but probably not to any pages. Or maybe it was a page, but not the parent one of the problematic components.

**Comment by ArosPrince** [comment]
And one more important thing I should have probably mentioned...

With 
`import Vuetify from "vuetify/lib"`

it does not work on my side at all. Everything on the frontend is totally broken.

Messing around with everything, I got it working by using this import instead:

`import Vuetify from "vuetify"`

No idea what that does, but with the exception of the aforementioned issues, it renders OK now.

I think I must be missing something very basic here.

**Comment by Hernanm0g** [comment]
Hi @ArosPrince . These issues are very very weird. I will try to reproduce them.

Tell me, are you working on a Windows PC?... Some of the core logic for [meteor-vuetify-loader](https://github.com/Hernanm0g/meteor-vuetify-loader) has been developed using Unix systems. That could be the root cause of this. Please, share the logs for the `npm run start` command.

Ill be back on the weekend, and try to debug that.

**Comment by ArosPrince** [comment]
Hi, I am sorry for the delay. Not sure why I haven't received any notification of your response.

So yes, this is a Windows PC I use for development. I use meteor up to deploy it then to a Ubuntu server. On the server it worked fine all the time if I remember correctly. But it has a different issues. It seems to me that it doesn't package styles that are bound dynamically. Like ``<v-row :class="`px-3 ${common.status}`">``

As for the logs... Will those help even if it works fine at this point? Or I can probably try a different Windows machine and see if that has the same problem.

**Comment by ArosPrince** [comment]
Hi @Hernanm0g ,

so I am not exactly sure this is related, but it may as well could be.

So one of the problems is that styles defined with VUE components won't ever get packaged. Like these:

```
<template>
  <v-row :class="px-3 online">
    
  </v-row>
</template>

<script>
export default {
  props: {
    // ...
  },
  data() {
    return {};
  },
  methods: {
    // ...
  },
};
</script>

<style>
.error {
  background-color: salmon;
}

.online,
.active {
  background-color: green;
}

.offline {
  background-color: grey;
}

.unpaired {
  background-color: grey;
}
</style>
```

No idea if this is a useful info, but I use meteor-up for deploying to the server. Locally, those styles work OK, but on the server the `div` for the `row` will have the class applied, but the style (for example `online`) won't appear among the styles.

So locally this looks like this:

![image](https://user-images.githubusercontent.com/25080989/145592979-09d07685-fcbe-4b01-be76-d32564e5d594.png)

But on the server, the style is missing:

![image](https://user-images.githubusercontent.com/25080989/145594573-5996647d-9e92-4b78-9afb-fe0af6c9f681.png)

Does that ring a bell? Again, sorry if this is totally unrelated. I am just doing my best (not being a frontend developer and all...). My thinking was that maybe if this happens with the styles I define by the components, it may as well happen to the Vuetify styles.

**Comment by Hernanm0g** [comment]
Hi @ArosPrince , thanks for pointing this out. In this package we are using a different logic for loading vuetify in dev and in prod. Please share here the content of the file: 
```imports/startup/plugins/vuetify.js```. I will address this tomorrow and will come back to you. Thanks for reporting this. Please also share the server details. so i can try to emulate in a cloud instance.

**Comment by ArosPrince** [comment]
Hi @Hernanm0g,

This is the content of the file:

```
import Vue from 'vue'
import '@mdi/font/css/materialdesignicons.min.css' // Ensure you are using css-loader

import minifyTheme from 'minify-css-string'

/*--------  The magic goes here  --------*/

// Use this import while developing
import Vuetify from "vuetify"

// IMPORTANT: Use this imports in production to reduce bundle size
// import Vuetify from "vuetify/lib/framework"
// import "vuetify/lib/util/colors"
// import "vuetify/lib/directives"

// TODO: find a proper way to import based on a conditional
// if(Meteor.isDevelopment){ ... }

Vue.use(Vuetify)

// Language
// Translation provided by Vuetify (javascript)
// import es from 'vuetify/es5/locale/es'


const opts = {
  theme: {
    options: { minifyTheme },
    themes: {
      light: {
        primary: '#E2E2E2',
        secondary: '#330066',
        success: '#3cd1c2',
        info: '#ffaa2c',
        error: '#f83e70'
      }
    }
  },
  icons: {
    iconfont: 'mdi', // default - only for display purposes
  },
}
export default new Vuetify(opts)

```

That is the file I mentioned at the beginning BTW, where I had to update the import: `import Vuetify from "vuetify/lib"` to `import Vuetify from "vuetify`

As for the server:
`20.04.3 LTS (GNU/Linux 5.11.0-1022-azure x86_64)`

It's Azure B1s instance, but that probably doesn't matter...

**Comment by Hernanm0g** [comment]
Hi @ArosPrince.
Checking your code i found this:
```html
<script>
export default {
  props: {
    // ...
  },
  data() {
    return {};
  },
  methods: {
    // ...
  },
};
</script>
```
Where you should have this:
```html
<script lang="js">  // <--- The magic goes here. You can also use lang="ts" or cpl="vuetify" in the newer versions
export default {
  props: {
    // ...
  },
  data() {
    return {};
  },
  methods: {
    // ...
  },
};
</script>
```

Try that and share if it works.
Here i leave you some screenshots on vswitch, dynamic classes and inline component classes working in my linux machine.

![Captura de pantalla de 2021-12-11 19-28-56](https://user-images.githubusercontent.com/36971322/145695994-8f99fe55-e7d8-4133-a2a7-16c99ddc12c0.png)
![Captura de pantalla de 2021-12-11 19-28-43](https://user-images.githubusercontent.com/36971322/145695996-090301e8-0e15-4546-8bb7-7cab5ceddb45.png)
![Captura de pantalla de 2021-12-11 19-28-23](https://user-images.githubusercontent.com/36971322/145695997-ac1479e0-2cae-4244-bc33-2fe488500ecd.png)
![Captura de pantalla de 2021-12-11 19-28-12](https://user-images.githubusercontent.com/36971322/145695998-685fcce0-1042-41b5-ac10-d393005af350.png)

**Comment by Hernanm0g** [comment]
By the way, @ArosPrince. In order to have all the potential in meteor_vuetify_loader you should use:

In prod:
```javascript
import Vuetify from "vuetify/lib/framework"
import "vuetify/lib/util/colors"
import "vuetify/lib/directives"
```
In dev:
```javascript
import Vuetify from "vuetify/lib"
```

**Comment by Hernanm0g** [comment]
Also @ArosPrince . 
I havent tested in a windows machine. If you have a chance, take a deep look into https://github.com/Hernanm0g/meteor-vuetify-loader.
Try to make this package work in your win machine and raise a PR. Ill happily review it.

**Comment by ArosPrince** [comment]
Hi @Hernanm0g,
sorry for the delay, I also seem to only have time on weekends...

I think those are two separate problems. Probably I should have created another issue not to confuse you and others...

Not sure if you got the part that the problem with the styles only happens with the deployed code. Not on the dev machine. 

I tried your suggestions, but that doesn't help. I tried adding `lang="js"` to the `script` tag, but that did not make any difference. I also tried `cpl="vuetify`, but again, no difference.

I also tried `scoped` style attribute, but again, no difference on the deployed server.

After googling stuff the entire day, I think it's this problem:
https://github.com/meteor-vue/vue-meteor/issues/188

Looks like the minifaction of styles won't work for VUE components in `/imports` folder. Will try to move them out, but the description seems to fit.

**Comment by ArosPrince** [comment]
@Hernanm0g OK, I was able to fix the problem by moving the styles defined by the component to `imports/ui/styles/mycomponentstyle.css`. Then I had to import the style inside the `<script>` tag. Importing it to `<style>` would not work.

This has to be a bug. I just can't tell on who's side. Whether it's one of meteor, meteor-vue, vuetify, or this boilerplate. No idea.

**Comment by Hernanm0g** [comment]
Hi @ArosPrince . Very nice investigation. I will try to check that
